### ISSUE TITLE
Successful install with errors

### ISSUE THREAD

**Issue by tushardave26** [MattOates/Stats#2]
Hello Matt,

I am a newbie to Perl6 and learning it at this moment. I came across your module and tried to install it with panda package manager. Unfortunately, one or more of the tests were failed, but the module got installed successfully. I found this fishy. Below is the installation log for your reference:

panda install Stats
==> Fetching Stats
==> Building Stats
Compiling lib/Stats.pm6 to mbc
Use of Nil in numeric context  in block  at /usr/local/Cellar/rakudo-star/2015.06/share/perl6/lib/Panda/Builder.pm:125
==> Testing Stats
===SORRY!=== Error while compiling t/stats.t
Undeclared routine:
    done-testing used at line 30. Did you mean 'done_testing'?

t/stats.t .. 
No subtests run 
## Test Summary Report

t/stats.t (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  1 wallclock secs ( 0.03 usr  0.00 sys +  1.22 cusr  0.05 csys =  1.30 CPU)
Result: FAIL
Use of Nil in numeric context  in block  at /usr/local/Cellar/rakudo-star/2015.06/share/perl6/lib/Panda/Tester.pm:36
==> Installing Stats
Copying blib/lib/Stats.pm6 to /usr/local/Cellar/rakudo-star/2015.06/share/perl6/site/lib/Stats.pm6
Copying blib/lib/Stats.pm6.moarvm to /usr/local/Cellar/rakudo-star/2015.06/share/perl6/site/lib/Stats.pm6.moarvm
==> Successfully installed Stats

Despite the test failure I tried to run your example code. Below is my one liner:

perl6 -MStats -e 'my @a = (1,2,3,4,5,6,6,3,2,9); summary @a;'

But I am not able to run it successfully. Below is the errors that I got:

Cannot call median(Parcel); none of these signatures match:
    (Baggy $x --> Real)
    (List $x --> Real)
  in sub quartiles at lib/Stats.pm6:63
  in sub summary at lib/Stats.pm6:148
  in block <unit> at -e:1

Can you please explain to me what's going on here? Is there a bug in your module or am I doing something wrong?

Thanks.

**Comment by rcmlz** [comment]
Hello, I could not reproduce the error using recent plain vanilla standard Rakudo Star installation, however, I also did not have any error when installing module Stats using "panda install Stats".

perl6 -MStats -e 'my @a = (1,2,3,4,5,6,6,3,2,9); say summary @a;'
(mean => 4.1 sd => 2.3 quartiles => (2 3.5 6) min => [1 2 3 4 5 6 6 3 2 9] max => [1 2 3 4 5 6 6 3 2 9])

**Comment by MattOates** [comment]
@tushardave26 thanks for your report, sorry for my incredibly slow response! This is a change in method name in newer versions of Rakudo's included Test module. Out of curiosity what version are you on `perl6 --version`. If this is a version bundled with a distro of Linux you might want to ask them to update it or have a go yourself.
